### PR TITLE
added support to filter by issuetype (similar to how priority list did it)

### PR DESCRIPTION
**Pull request by SxMShaDoW**
I added the "hide sub-task option" but it doesn't do anything. I would have to look into the code more and I don't really have the time for that. Feel free to exclude it or change it around. Essentially we want to also check fields.issuetype.subtask and see if it is false/true and store that somewhere. So we can then filter all the ones that are true. 

Also need a new .png for the issuetype.

### CODE REVIEW

**Comment by SxMShaDoW** [comment]
we should also remove some of the console.logs we have in there. I noticed a lot of them fire off (I even added a few so we can remove those)

**Comment by webkhung** [comment]
@SxMShaDoW I got it working.  I haven't cleaned up the console log yet.  I see that you have many filters setup on your JIRA board.  Can you leave them there until after my presentation?  I want to use it as example or how the plugin can speed things up.

**Comment by SxMShaDoW** [comment]
Sure. Great job per usual. I wasn't planning on deleting them. Feel free to
close out the issues in the backlog of the repo. Btw, I think your plugin
has some really awesome features. You crushed it!

A future improvement would be to be able to customize what to show and what
not to (like we don't use release notes and such) and where the plugin is
located (the floating thing is kind of tough sometimes).

Let me know if you ever wanted me to show this to a few of my atlassian
colleagues.

Cheers

**Comment by webkhung** [comment]
@SxMShaDoW I moved the toolbar higher because it is getting longer.  The floating box is now on the header area so it doesn't block the cards that much. I also changed the plugin so that the release note button only show on my jira board :D  
Who are your atlassian collegues?  They are not your intuit collegues?  :D 
Maybe you can invite them to my presentation if they are in San Diego and are free next Tuesday 12pm.  Are you coming to my presentation?

**Comment by SxMShaDoW** [comment]
Just people I have met via the Conference that may be interested in some of the work you have done. Meant to say friends/people i talk to occasionally haah :). Atlassian is based out of Sydney + bay area. So sorry I can't invite them :(

**Comment by webkhung** [comment]
Yes feel free to show it to your friends. As you know I have a public version "Jira Agile Instant" but I haven't upgraded it with all the stuffs we added recently.

**Comment by SxMShaDoW** [comment]
Is the public version in a different github repo? I didn't see an extra
branch here.

**Comment by webkhung** [comment]
It is in https://github.com/webkhung/jira_agile_instant
The reason I make a different repo is I don't want the intuit specific stuffs in the same repo (although there is no sensitive information). For example I think https://github.com/webkhung/jira_on_steroid/blob/master/intuit.js only works for intuit.

**Comment by SxMShaDoW** [comment]
Makes sense. That probably would be a nightmare to diff haha. Another task
for another day!

**Comment by webkhung** [comment]
yea.  but there are 300 users!

**Comment by SxMShaDoW** [comment]
In the future when its polished I'll see if I can get a blog post from
Atlassian about it! Thats when the numbers would shoot up! haha

**Comment by webkhung** [comment]
cool.  I am interested to see how the plugin works with the new environment.

**Pull request merged**
